# Generated by Django 5.0.1 on 2024-03-27 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='images/placeholder_image.jpg', upload_to='website/images/')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreEverything',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn_performance', models.IntegerField()),
                ('pn_elegance', models.IntegerField()),
                ('pn_beauty', models.IntegerField()),
                ('pn_audience', models.IntegerField()),
                ('sw_poise', models.IntegerField()),
                ('sw_body', models.IntegerField()),
                ('sw_beauty', models.IntegerField()),
                ('sw_audience', models.IntegerField()),
                ('eg_poise', models.IntegerField()),
                ('eg_elegance', models.IntegerField()),
                ('eg_beauty', models.IntegerField()),
                ('eg_audience', models.IntegerField()),
                ('fq_wisdom', models.IntegerField()),
                ('fq_charisma', models.IntegerField()),
                ('fq_intelligence', models.IntegerField()),
                ('fq_persuasion', models.IntegerField()),
                ('pn_total', models.IntegerField(default=0)),
                ('sw_total', models.IntegerField(default=0)),
                ('eg_total', models.IntegerField(default=0)),
                ('fq_total', models.IntegerField(default=0)),
                ('t_avg', models.IntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.record')),
                ('judge', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
