# Generated by Django 5.0.1 on 2024-03-24 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_record_address_remove_record_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreEverything',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn_performance', models.IntegerField()),
                ('pn_elegance', models.IntegerField()),
                ('pn_beauty', models.IntegerField()),
                ('pn_audience', models.IntegerField()),
                ('sw_poise', models.IntegerField()),
                ('sw_body', models.IntegerField()),
                ('sw_beauty', models.IntegerField()),
                ('sw_audience', models.IntegerField()),
                ('eg_poise', models.IntegerField()),
                ('eg_elegance', models.IntegerField()),
                ('eg_beauty', models.IntegerField()),
                ('eg_audience', models.IntegerField()),
                ('fq_wisdom', models.IntegerField()),
                ('fq_charisma', models.IntegerField()),
                ('fq_intelligence', models.IntegerField()),
                ('fq_persuasion', models.IntegerField()),
                ('pn_total', models.IntegerField()),
                ('sw_total', models.IntegerField()),
                ('eg_total', models.IntegerField()),
                ('fq_total', models.IntegerField()),
                ('t_avg', models.IntegerField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.record')),
                ('judge', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
