# Generated by Django 5.0.1 on 2024-03-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_candidate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(default='static/images/placeholder_image.jpg', upload_to='website/images/'),
        ),
    ]
