# Generated by Django 5.0.1 on 2024-03-29 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='status',
        ),
    ]
