# Generated by Django 5.0.1 on 2024-03-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_record_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='image',
            field=models.ImageField(default='images/placeholder_image.jpg', upload_to='website/images/'),
        ),
    ]
