# Generated by Django 5.0.1 on 2024-03-27 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_record_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='image',
        ),
    ]
